#!/usr/bin/env bash
# agent_env_test.sh — tools/agent-env.sh, which puts the sibling toolchain on
# PATH for agent shells.
#
# Every case here is a bug that shipped. This tool runs from a PreToolUse hook
# on every shell command an agent issues, so its failure modes are silent and
# total: a shell that exits, a PATH that grows without bound, a cache emptied
# at the one moment it was needed.
. "$(dirname "$0")/helpers.sh"

ws="$(make_workspace)"
collection="$ws/demo"
mkdir -p "$collection"
cp -R "$ws/main/harness" "$collection/harness"
agent_env="$collection/harness/tools/agent-env.sh"

# A toolchain prefix that exists on disk but is nothing like a real PATH, so
# an assertion cannot pass by accident on the developer's own environment.
fake_bin="$(mktemp_dir bins)"
mkdir -p "$fake_bin/alpha" "$fake_bin/beta"
prefix="$fake_bin/alpha:$fake_bin/beta"

write_cache() { # seed .env.toolchain directly; mise may not be installed here
  cat > "$collection/.env.toolchain" <<EOF
# Generated by harness/tools/agent-env.sh — machine-local toolchain bins.
WTC_TOOLCHAIN_PATH=$prefix
EOF
}
write_cache

# Run agent-env.sh with a controlled environment: no mise, a known PATH, and
# the collection named explicitly so it never walks up into a real workspace.
#
# `</dev/null` is load-bearing, not tidiness. When stdin is a socket, bash
# applies its "started by a remote shell daemon" heuristic and sources
# ~/.bashrc for a non-interactive shell *instead of* $BASH_ENV. Inheriting the
# stdin of whatever ran the suite therefore decides whether the BASH_ENV case
# below tests anything — which is exactly the intermittent failure that led
# here. Closing stdin makes it deterministic.
in_clean_shell() { # <bash -c script> — stdin closed
  env -i HOME="$HOME" PATH=/usr/bin:/bin \
      CLAUDE_PROJECT_DIR="$collection" \
      /bin/bash -c "$1" </dev/null
}

# Same, but stdin passes through — for --wrap, which reads its hook payload
# from it. A pipe is not a socket, so bash still honours BASH_ENV here; it is
# only an inherited socket that triggers the remote-shell heuristic.
in_clean_shell_stdin() { # <bash -c script>
  env -i HOME="$HOME" PATH=/usr/bin:/bin \
      CLAUDE_PROJECT_DIR="$collection" \
      /bin/bash -c "$1"
}

# --- sourced mode must not kill the calling shell ---------------------------
# The header advertises `. agent-env.sh` and BASH_ENV. A trailing `exit 0`
# made both take the *calling* shell down: the shell simply stopped, with no
# error, so under BASH_ENV every command in the session became a silent no-op.

it "sourcing it leaves the shell alive"
out="$(in_clean_shell ". '$agent_env'; echo STILL_ALIVE")"
assert_eq "STILL_ALIVE" "$out"

it "sourcing it applies the prefix to the calling shell"
out="$(in_clean_shell ". '$agent_env'; echo \"\$PATH\"")"
assert_contains "$out" "$fake_bin/alpha"
out="$(in_clean_shell ". '$agent_env'; echo \"\${WTC_AGENT_ENV:-unset}\"")"
assert_eq "1" "$out"

it "sourcing it is silent on stdout and stderr"
# Anything printed here lands in the middle of whatever the shell was doing,
# and under BASH_ENV that is every command.
#
# Both streams, merged at the outer capture. Writing `2>&1 >/dev/null` inside
# would point stderr at the original stdout and *then* send stdout to
# /dev/null — checking stderr alone, which is the half less likely to be
# wrong.
out="$(in_clean_shell ". '$agent_env'; :" 2>&1)"
assert_empty "$out"

it "BASH_ENV applies it to a non-interactive shell"
# This is the case agent CLIs actually produce, and the reason the sourced
# mode exists at all — with the caveat that bash only consults BASH_ENV when
# it does not think it was started by a remote shell daemon. See
# in_clean_shell above, and instructions/hooks-and-env.md.
out="$(env -i HOME="$HOME" PATH=/usr/bin:/bin \
      CLAUDE_PROJECT_DIR="$collection" BASH_ENV="$agent_env" \
      /bin/bash -c 'echo "$PATH"' </dev/null)"
assert_contains "$out" "$fake_bin/alpha"

# --- PATH hygiene -----------------------------------------------------------

it "eval-ing it repeatedly does not grow PATH"
# `.envrc`, the herdr workspace env and the PreToolUse hook can all apply the
# same prefix to one shell. Without a guard each eval prepends another copy.
script="eval \"\$(bash '$agent_env')\"; a=\$(echo \"\$PATH\" | tr : '\n' | wc -l)
eval \"\$(bash '$agent_env')\"; eval \"\$(bash '$agent_env')\"
b=\$(echo \"\$PATH\" | tr : '\n' | wc -l)
echo \"\$a \$b\""
set -- $(in_clean_shell "$script")
assert_eq "$1" "$2" "PATH length after 1 eval vs 3"

it "an empty PATH gains no empty element"
# An empty element in PATH means the current directory. In something that runs
# on every tool call that is a footgun, not a nit.
out="$(env -i HOME="$HOME" CLAUDE_PROJECT_DIR="$collection" \
      /bin/bash -c "unset PATH; eval \"\$(/bin/bash '$agent_env')\"; echo \":\$PATH:\"" </dev/null)"
assert_not_contains "$out" "::"

# --- the cache --------------------------------------------------------------

it "--write keeps a good cache when mise is missing"
# The SessionStart hook is exactly the place likely to run in a shell too bare
# to find mise. Writing an empty WTC_TOOLCHAIN_PATH there reintroduces the bug
# the tool exists to fix, at the moment the cache matters most.
write_cache
before="$(cat "$collection/.env.toolchain")"
in_clean_shell "'$agent_env' --write"
after="$(cat "$collection/.env.toolchain")"
assert_eq "$before" "$after" "cache survives a mise-less --write"

it "--print-path reads the cache back"
out="$(in_clean_shell "'$agent_env' --print-path")"
assert_eq "$prefix" "$out"

# --- the PreToolUse wrapper -------------------------------------------------

# --wrap parses its hook payload with python3, and is documented to fail open
# without it: consume stdin, rewrite nothing, exit 0. Both halves are real
# behaviour, so test whichever one this machine can reach rather than assuming
# an interpreter that a minimal Linux image does not have.
have_python3=no
in_clean_shell "command -v python3 >/dev/null" && have_python3=yes

if [ "$have_python3" = yes ]; then
  it "--wrap rewrites a command to apply the prefix first"
  out="$(printf '{"tool_input":{"command":"echo hi"}}' | in_clean_shell_stdin "'$agent_env' --wrap")"
  assert_contains "$out" "updatedInput"
  assert_contains "$out" "wtc-agent-env"
else
  it "--wrap fails open when python3 is missing"
  out="$(printf '{"tool_input":{"command":"echo hi"}}' | in_clean_shell_stdin "'$agent_env' --wrap")"
  assert_empty "$out" "no rewrite without python3"
fi

# The cases below assert that nothing is rewritten, which is equally true with
# or without python3 — no branch needed.
it "--wrap is idempotent on an already-wrapped command"
already='{"tool_input":{"command":"# wtc-agent-env\neval x\necho hi"}}'
out="$(printf '%s' "$already" | in_clean_shell_stdin "'$agent_env' --wrap")"
assert_empty "$out" "no second wrap"

it "--wrap no-ops on input it cannot use"
for payload in '' 'not json at all' '{}' '{"tool_input":{}}' '{"tool_input":{"command":""}}'; do
  out="$(printf '%s' "$payload" | in_clean_shell_stdin "'$agent_env' --wrap")"
  assert_empty "$out" "no rewrite for: ${payload:-<empty>}"
done

it "--wrap exits 0 even when it declines to rewrite"
# A nonzero exit from a PreToolUse hook can block the tool call it was meant
# to help.
assert_ok sh -c "printf 'garbage' | env -i HOME='$HOME' PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR='$collection' /bin/bash '$agent_env' --wrap"

# --- fail-open --------------------------------------------------------------

it "it exits 0 outside any collection"
nowhere="$(mktemp_dir nowhere)"
assert_ok env -i HOME="$HOME" PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR="$nowhere" \
  /bin/bash "$agent_env" --write

it "sourcing it outside any collection still leaves the shell alive"
# The other half of the `exit` bug: the early "no collection here" return was
# also an exit, so a BASH_ENV pointed at a retired collection killed the shell.
out="$(env -i HOME="$HOME" PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR="$nowhere" \
      /bin/bash -c ". '$agent_env'; echo STILL_ALIVE" </dev/null)"
assert_eq "STILL_ALIVE" "$out"

# --- the hook command that reaches this tool --------------------------------
# agent-env.json is what Claude/Cursor/grok actually run, and invoke.sh goes to
# some trouble to be cwd-independent — it walks up from CLAUDE_PROJECT_DIR,
# GROK_WORKSPACE_ROOT or PWD. That care was defeated by the one step before it:
# the JSON named invoke.sh by the bare relative path `harness/hooks/invoke.sh`,
# so the moment a hook ran with a cwd below the collection root the shell could
# not find it at all —
#
#   /bin/sh: harness/hooks/invoke.sh: No such file or directory
#
# — on *every* shell command, with exit 127, where the documented contract is
# to fail open and exit 0.

hook_command() { # <--write|--wrap> -> the command string agent-env.json carries
  python3 - "$collection/harness/hooks/agent-env.json" "$1" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
event = 'SessionStart' if sys.argv[2] == '--write' else 'PreToolUse'
print(cfg['hooks'][event][0]['hooks'][0]['command'])
PY
}

# A collection whose invoke.sh only reports that it was reached: this asserts
# the locator in the JSON, which is the part that was wrong. The real chain
# beyond invoke.sh is what every other case in this file covers.
marker_root="$(mktemp_dir hookloc)"
mkdir -p "$marker_root/coll/harness/hooks" "$marker_root/coll/repo/deep"
printf '#!/bin/sh\necho "reached $1"\n' > "$marker_root/coll/harness/hooks/invoke.sh"
chmod +x "$marker_root/coll/harness/hooks/invoke.sh"

run_hook_from() { # <dir> <mode> -> whatever the hook command printed
  ( cd "$1" && env -u CLAUDE_PROJECT_DIR -u GROK_WORKSPACE_ROOT \
      /bin/sh -c "$(hook_command "$2")" 2>&1 )
}

it "the hook command reaches invoke.sh from the collection root"
assert_eq "reached --wrap" "$(run_hook_from "$marker_root/coll" --wrap)"
assert_eq "reached --write" "$(run_hook_from "$marker_root/coll" --write)"

it "the hook command reaches invoke.sh from a subdirectory"
# The bug: a hook firing with cwd anywhere below the collection root.
assert_eq "reached --wrap" "$(run_hook_from "$marker_root/coll/harness" --wrap)"
assert_eq "reached --wrap" "$(run_hook_from "$marker_root/coll/repo/deep" --wrap)"

it "the hook command honours the runtime's project root over cwd"
out="$(cd / && CLAUDE_PROJECT_DIR="$marker_root/coll/repo/deep" \
  /bin/sh -c "$(hook_command --wrap)" 2>&1)"
assert_eq "reached --wrap" "$out"
out="$(cd / && env -u CLAUDE_PROJECT_DIR GROK_WORKSPACE_ROOT="$marker_root/coll" \
  /bin/sh -c "$(hook_command --wrap)" 2>&1)"
assert_eq "reached --wrap" "$out" "grok names its root differently"

it "the hook command fails open outside any collection"
# Silence and 0, not 127 and a message on every shell command an agent runs.
out="$(run_hook_from "$marker_root" --wrap)"; rc=$?
assert_eq 0 "$rc"
assert_eq "" "$out"

it "the hook command names no bare relative path"
# The regression in one line: a command that starts from a relative path is
# a command that only works from one directory.
for mode in --write --wrap; do
  cmd="$(hook_command "$mode")"
  if printf '%s' "$cmd" | grep -qE '(^|[^/A-Za-z_-])harness/hooks/invoke\.sh'; then
    _fail "agent-env.json $mode reaches invoke.sh by a relative path" "$cmd"
  else
    _pass "agent-env.json $mode does not depend on cwd"
  fi
done
