#!/usr/bin/env bash
# refresh-configs.sh — (re)generate the local .harness-repos from the
# workspace .bare/ directory and cross-check it against .harness-repos.yml.
#
# Bash 3.2-safe (macOS default): no mapfile, no associative arrays.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: tools/refresh-configs.sh

Regenerates the local .harness-repos (name=bare-path, gitignored) from the
workspace .bare/ directory, and warns about bares missing from the tracked
.harness-repos.yml registry or listed there without a local clone.

Takes no options. Idempotent — run it whenever a bare is added or removed.
EOF
  exit "${1:-1}"
}

# Parse before doing anything: this tool writes a file, so `--help` must not
# be answered by going ahead and writing it.
case "${1:-}" in
  -h|--help) usage 0 ;;
  "") ;;
  *) echo "unknown option: $1" >&2; usage ;;
esac

script_dir="$(cd "$(dirname "$0")" && pwd)"
harness_dir="$(dirname "$script_dir")"
# Older init hooks call this path. Use the native registry writer after install;
# keep the shell implementation for a collection being bootstrapped.
collection="$(dirname "$harness_dir")"
if (cd "$collection" && command -v wtc >/dev/null 2>&1 && wtc registry refresh --help >/dev/null 2>&1); then
  cd "$collection"
  exec wtc registry refresh --collection "$collection"
fi
root="$harness_dir"
while [ "$root" != "/" ] && [ ! -d "$root/.bare" ]; do
  root="$(dirname "$root")"
done
[ -d "$root/.bare" ] || { echo "error: no .bare/ found above $script_dir" >&2; exit 1; }

registry="$harness_dir/.harness-repos.yml"
out="$harness_dir/.harness-repos"

echo "workspace root: $root"

tmp="$out.tmp.$$"
{
  echo "# Generated by tools/refresh-configs.sh — local bare-owner paths."
  echo "# Tracked counterpart: .harness-repos.yml"
  for bare in "$root"/.bare/*.git; do
    [ -d "$bare" ] || continue
    name="$(basename "$bare" .git)"
    echo "$name=$bare"
  done
} > "$tmp"
mv "$tmp" "$out"
echo "wrote $out:"
grep -v '^#' "$out" | sed 's/^/  /'

# Cross-check against the tracked registry.
if [ -f "$registry" ]; then
  status=0
  for name in $(awk '$1 == "-" && $2 == "name:" { print $3 }' "$registry"); do
    if ! grep -q "^$name=" "$out"; then
      echo "note: '$name' is in the registry but has no bare owner yet (clone it when a collection needs it)"
    fi
  done
  while IFS='=' read -r name path; do
    case "$name" in ''|\#*) continue ;; esac
    if ! awk '$1 == "-" && $2 == "name:" { print $3 }' "$registry" | grep -qx "$name"; then
      echo "WARNING: bare '$name' exists locally but is not in .harness-repos.yml — add it to the registry" >&2
      status=1
    fi
  done < "$out"
  exit "$status"
else
  echo "WARNING: $registry missing — no cross-check performed" >&2
fi
